routes/web.php
<?php

use App\Http\Controllers\CampaignController;
use App\Http\Controllers\HospitalController;
use App\Http\Controllers\HospitalLoginController;
use App\Http\Controllers\HospitalServicesController;
use App\Http\Controllers\PatientController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DataFeedController;
use App\Http\Controllers\DashboardController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::post('register', [HospitalController::class, 'register']);

Route::get('login/hospital', [HospitalLoginController::class, 'showLoginForm'])->name('hospital.login');
Route::post('login/hospital', [HospitalLoginController::class, 'login']);



Route::redirect('/', 'login');

Route::middleware(['auth:sanctum', 'verified'])->group(function () {

    // Route for the getting the data feed
    Route::get('/json-data-feed', [DataFeedController::class, 'getDataFeed'])->name('json_data_feed');

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('services',DashboardController::class);
    Route::resource('hospitals', HospitalController::class);
    Route::put('hospitals/approve/{hospital}', [HospitalController::class, 'approve'])->name('hospitals.approve');
    Route::put('hospitals/disapprove/{hospital}', [HospitalController::class, 'disapprove'])->name('hospitals.disapprove');

    Route::fallback(function() {
        return view('pages/utility/404');
    });


});


Route::middleware(['auth:hospital'])->group(function () {
    Route::resource('patients', PatientController::class);
    Route::resource('campaigns', CampaignController::class);
    Route::resource('hospital-services',\App\Http\Controllers\HospitalServicesController::class);

    Route::get('hospital-services/{hospital}/update-view', [HospitalServicesController::class, 'updateServicesView'])
        ->name('hospital-services.update-view');

   /* Route::put('hospital-services/{hospital}', [HospitalServicesController::class, 'updateServices'])
        ->name('hospital-services.update');*/

    Route::get('/hospital/update-password', [HospitalController::class,'editPassword'])->name('hospital.editPassword');
    Route::post('/hospital/update-password', [HospitalController::class,'updatePassword'])->name('hospital.updatePassword');




});

app/Models/Hospital.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Hospital  extends Authenticatable

{
    use HasFactory;

    protected $fillable = [
        'name',
        'contact_number',
        'email',
        'address',
        'city',
        'password',
        'is_approved', // Add this line
    ];

    public function services()
    {
        return $this->belongsToMany(Service::class)
            ->withPivot('status')
            ->withTimestamps();


    }

}

app/Http/Controllers/HospitalController.php
<?php

namespace App\Http\Controllers;

use App\Models\Hospital;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class HospitalController extends Controller
{

    public function register(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'contact_number' => 'required|string|max:255',
            'email' => 'required|email|unique:hospitals',
            'address' => 'required|string|max:255',
            'city' => 'required|string|max:255',
            'password' => 'required|string|min:8|confirmed',
        ]);

        Hospital::create([
            'name' => $request->name,
            'contact_number' => $request->contact_number,
            'email' => $request->email,
            'address' => $request->address,
            'city' => $request->city,
            'password' => Hash::make($request->password),
        ]);

        return redirect()->route('login')->with('success', 'Hospital registered successfully! You can now log in.');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $hospitals = Hospital::paginate(10);
        return view('pages.dashboard.hospital.index', compact('hospitals'));
    }

    public function create()
    {
        return view('pages.dashboard.hospital.create');
    }

    public function store(Request $request)
    {
        // Validation and store logic
    }

    public function edit($id)
    {
        $hospital = Hospital::findOrFail($id);
        return view('pages.dashboard.hospital.edit', compact('hospital'));
    }

    public function update(Request $request, $id)
    {
        $hospital = Hospital::findOrFail($id);

        // Validation and update logic
        $hospital->update($request->all());

        return redirect()->route('hospitals.index')->with('success', 'Hospital updated successfully');
    }

    public function destroy($id)
    {
        // Delete logic
    }

    public function approve(Hospital $hospital)
    {
        $hospital->update(['is_approved' => true]);
        return    $this->index();
    }

    public function disapprove(Hospital $hospital)
    {
        $hospital->update(['is_approved' => false]);
        return redirect()->route('hospitals.index')->with('success', 'Hospital disapproved successfully');
    }

    public function show($id)
    {
        $hospital = Hospital::findOrFail($id);
        return view('pages.dashboard.hospital.show', compact('hospital'));
    }

    public function editPassword()
    {
        return view('pages.hospital.update-password');
    }

    public function updatePassword(Request $request)
    {

        $user = auth()->guard('hospital')->user();

        if (Hash::check($request->current_password, $user->password)) {
            $user->update([
                'password' => Hash::make($request->password),
            ]);

            return redirect()->route('hospital.editPassword')->with('success', 'Password updated successfully.');
        } else {
            return redirect()->route('hospital.editPassword')->with('error', 'Current password is incorrect.');
        }
    }

}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/pages/hospital/dashboard.blade.php
<x-app-layout>
    <div class="px-4 sm:px-6 lg:px-8 py-8 w-full max-w-9xl mx-auto">

        <!-- Welcome banner -->
        <x-dashboard.welcome-banner />

        <!-- Dashboard actions -->
        <div class="sm:flex sm:justify-between sm:items-center mb-8">

        </div>

            <!-- Right: Actions -->
            <div class="grid grid-flow-col sm:auto-cols-max justify-start sm:justify-end gap-2">
            <h2 class="text-2xl md:text-3xl text-slate-800 dark:text-slate-100 font-bold mb-1">Patients List</h2>
                <!-- Add view button -->
                {{--<a href="{{ route('patient.create') }}"
                   class="bg-green-700 hover:bg-red-700 text-white py-2 px-4 rounded">
                    <span class="hidden xs:block ml-2">Add Patients</span>
                </a>--}}


            </div>

        </div>

    <div class="mb-3 ml-4">
        <label for="search" class="block text-sm font-medium text-gray-700">Search:</label>
        <input type="text" id="search" class="mt-1 p-2  border border-gray-300 rounded-md text-sm">
    </div>

    <table id="patient-table"  class="w-full border-collapse border table" data-searchable="true">
            <thead>
            <tr>
                <th class="p-4 bg-gray-100 border border-gray-300">ID</th>
                <th class="p-4 bg-gray-100 border border-gray-300">Name</th>
                <th class="p-4 bg-gray-100 border border-gray-300">Clinic</th>
                <th class="p-4 bg-gray-100 border border-gray-300">Mobile</th>
                <th class="p-4 bg-gray-100 border border-gray-300">Description</th>
                <th class="p-4 bg-gray-100 border border-gray-300">Location (Lat)(Lng)</th>
                <th class="p-4 bg-gray-100 border border-gray-300">Date & Time</th>
                <th class="p-4 bg-gray-100 border border-gray-300">Action</th>
                <!-- Other columns -->
            </tr>
            </thead>
            <tbody>
            @foreach($patients as $patient)
                <tr class="bg-white hover:bg-gray-100">
                    <td class="p-4 border border-gray-300">{{ $loop->index+1 }}</td>
                    <td class="p-4 border border-gray-300">{{ $patient->name }}</td>
                    <td class="p-4 border border-gray-300">{{ $patient->clinic }}</td>
                    <td class="p-4 border border-gray-300">{{ $patient->mobile }}</td>
                    <td class="p-4 border border-gray-300">{{ $patient->description }}</td>
                    <td class="p-4 border border-gray-300">{{ ($patient->lat)}} {{($patient->lng) }}</td>
                    <td class="p-4 border border-gray-300">{{ $patient->datetime }}</td>
                    <td class="p-4 border border-gray-300">
                       {{-- <a href="{{ route('patients.edit', ['patient' => $patient->id]) }}"
                           class="bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded">
                            Edit
                        </a>--}}
                        <form method="POST" action="{{ route('patients.destroy', $patient->id) }}" class="inline">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="text-red-500 hover:text-red-700 focus:outline-none btn">
                                Delete
                            </button>
                        </form>

                    </td>
                    <!-- Other cells -->
                </tr>
            @endforeach
            </tbody>
        </table>

        {{ $patients->links() }} <!-- Display pagination links -->

    @push('script')
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://cdn.datatables.net/1.11.6/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.datatables.net/1.11.6/js/dataTables.bootstrap4.min.js"></script>

        <script>
            $(document).ready(function () {
                var table = $('#patient-table').DataTable({
                    "paging": true,
                    "ordering": true,
                    "searching": true, // Enable search functionality
                    "language": {
                        "search": "Search:",
                        "searchPlaceholder": "Enter search term"
                    }
                });

                $('#search').on('keyup', function () {
                    table.search(this.value).draw(); // Apply the search filter to the DataTable
                });
            });
        </script>

        <script>
            $(document).ready(function () {
                var table = $('#patient-table').DataTable({
                    "paging": true,
                    "ordering": true,
                    "searching": true, // Enable search functionality
                    "language": {
                        "search": "Search:",
                        "searchPlaceholder": "Enter search term"
                    }
                });

                $('#search').on('keyup', function () {
                    table.search(this.value).draw(); // Apply the search filter to the DataTable
                });
            });
        </script>

        @endpush

    </div>



</x-app-layout>