routes/web.php
<?php

use App\Http\Controllers\CampaignController;
use App\Http\Controllers\HospitalController;
use App\Http\Controllers\HospitalLoginController;
use App\Http\Controllers\HospitalServicesController;
use App\Http\Controllers\PatientController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DataFeedController;
use App\Http\Controllers\DashboardController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::post('register', [HospitalController::class, 'register']);

Route::get('login/hospital', [HospitalLoginController::class, 'showLoginForm'])->name('hospital.login');
Route::post('login/hospital', [HospitalLoginController::class, 'login']);



Route::redirect('/', 'login');

Route::middleware(['auth:sanctum', 'verified'])->group(function () {

    // Route for the getting the data feed
    Route::get('/json-data-feed', [DataFeedController::class, 'getDataFeed'])->name('json_data_feed');

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('services',DashboardController::class);
    Route::resource('hospitals', HospitalController::class);
    Route::put('hospitals/approve/{hospital}', [HospitalController::class, 'approve'])->name('hospitals.approve');
    Route::put('hospitals/disapprove/{hospital}', [HospitalController::class, 'disapprove'])->name('hospitals.disapprove');

    Route::fallback(function() {
        return view('pages/utility/404');
    });


});


Route::middleware(['auth:hospital'])->group(function () {
    Route::resource('patients', PatientController::class);
    Route::resource('campaigns', CampaignController::class);
    Route::resource('hospital-services',\App\Http\Controllers\HospitalServicesController::class);

    Route::get('hospital-services/{hospital}/update-view', [HospitalServicesController::class, 'updateServicesView'])
        ->name('hospital-services.update-view');

   /* Route::put('hospital-services/{hospital}', [HospitalServicesController::class, 'updateServices'])
        ->name('hospital-services.update');*/

    Route::get('/hospital/update-password', [HospitalController::class,'editPassword'])->name('hospital.editPassword');
    Route::post('/hospital/update-password', [HospitalController::class,'updatePassword'])->name('hospital.updatePassword');




});

app/Models/Hospital.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Hospital  extends Authenticatable

{
    use HasFactory;

    protected $fillable = [
        'name',
        'contact_number',
        'email',
        'address',
        'city',
        'password',
        'is_approved', // Add this line
    ];

    public function services()
    {
        return $this->belongsToMany(Service::class)
            ->withPivot('status')
            ->withTimestamps();


    }

}

app/Http/Controllers/DashboardController.php
<?php

    namespace App\Http\Controllers;

    use App\Models\Service;
    use Illuminate\Http\Request;
    use Illuminate\Support\Facades\Http;
    use App\Models\DataFeed;
    use Carbon\Carbon;

    class DashboardController extends Controller
    {

        /**
         * Displays the dashboard screen
         *
         * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
         */
        public function index()
        {
            $services = Service::paginate(10);

            return view('pages.dashboard.dashboard', compact('services'));

           // return view('pages/dashboard/dashboard', compact('dataFeed'));
        }
        public function show($id)
        {
            // Display the details of a specific service
        }
        public function create()
        {
            return view('pages.dashboard.services.create');
        }

        public function store(Request $request)
        {
            $validatedData = $request->validate([
                'name' => 'required|string|max:255',
                'status' => 'required|in:Available,Busy',
            ]);

            Service::create($validatedData);

            return redirect()->route('services.index')->with('success', 'Service created successfully');
        }

        public function edit($id)
        {
            $service = Service::findOrFail($id);
            return view('pages.dashboard.services.edit', compact('service'));
        }

        public function update(Request $request, $id)
        {
            $service = Service::findOrFail($id);
            $service->update($request->all());
            return redirect()->route('services.index')->with('success', 'Service updated successfully');
        }

        public function destroy($id)
        {

            $service = Service::findOrFail($id);
            $service->delete();
            return $this->index();
        }
    }

app/Http/Controllers/HospitalController.php
<?php

namespace App\Http\Controllers;

use App\Models\Hospital;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class HospitalController extends Controller
{

    public function register(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'contact_number' => 'required|string|max:255',
            'email' => 'required|email|unique:hospitals',
            'address' => 'required|string|max:255',
            'city' => 'required|string|max:255',
            'password' => 'required|string|min:8|confirmed',
        ]);

        Hospital::create([
            'name' => $request->name,
            'contact_number' => $request->contact_number,
            'email' => $request->email,
            'address' => $request->address,
            'city' => $request->city,
            'password' => Hash::make($request->password),
        ]);

        return redirect()->route('login')->with('success', 'Hospital registered successfully! You can now log in.');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $hospitals = Hospital::paginate(10);
        return view('pages.dashboard.hospital.index', compact('hospitals'));
    }

    public function create()
    {
        return view('pages.dashboard.hospital.create');
    }

    public function store(Request $request)
    {
        // Validation and store logic
    }

    public function edit($id)
    {
        $hospital = Hospital::findOrFail($id);
        return view('pages.dashboard.hospital.edit', compact('hospital'));
    }

    public function update(Request $request, $id)
    {
        $hospital = Hospital::findOrFail($id);

        // Validation and update logic
        $hospital->update($request->all());

        return redirect()->route('hospitals.index')->with('success', 'Hospital updated successfully');
    }

    public function destroy($id)
    {
        // Delete logic
    }

    public function approve(Hospital $hospital)
    {
        $hospital->update(['is_approved' => true]);
        return    $this->index();
    }

    public function disapprove(Hospital $hospital)
    {
        $hospital->update(['is_approved' => false]);
        return redirect()->route('hospitals.index')->with('success', 'Hospital disapproved successfully');
    }

    public function show($id)
    {
        $hospital = Hospital::findOrFail($id);
        return view('pages.dashboard.hospital.show', compact('hospital'));
    }

    public function editPassword()
    {
        return view('pages.hospital.update-password');
    }

    public function updatePassword(Request $request)
    {

        $user = auth()->guard('hospital')->user();

        if (Hash::check($request->current_password, $user->password)) {
            $user->update([
                'password' => Hash::make($request->password),
            ]);

            return redirect()->route('hospital.editPassword')->with('success', 'Password updated successfully.');
        } else {
            return redirect()->route('hospital.editPassword')->with('error', 'Current password is incorrect.');
        }
    }

}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/pages/dashboard/hospital/create.blade.php
<x-app-layout>
    <div class="px-4 sm:px-6 lg:px-8 py-8 w-full max-w-9xl mx-auto">
        <div class="max-w-md mx-auto mt-8">
            <h1 class="text-2xl font-semibold mb-4">Add Hospital</h1>
            <form method="POST" action="{{ route('hospitals.store') }}" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
                @csrf
                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="name">Name:</label>
                    <input type="text" name="name" value="{{ old('name') }}" required class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline @error('name') border-red-500 @enderror">
                    @error('name')
                    <p class="text-red-500 text-xs italic">{{ $message }}</p>
                    @enderror
                </div>
                <!-- Repeat for other attributes -->
                <div class="flex items-center justify-between">
                    <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                        Create
                    </button>
                </div>
            </form>
        </div>
    </div>
</x-app-layout>

resources/views/pages/dashboard/hospital/edit.blade.php
<x-app-layout>
    <div class="px-4 sm:px-6 lg:px-8 py-8 w-full max-w-9xl mx-auto">
        <div class="max-w-md mx-auto mt-8">
            <h1 class="text-2xl font-semibold mb-4">Edit Hospital</h1>
            <form method="POST" action="{{ route('hospitals.update', $hospital->id) }}" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
                @csrf
                @method('PUT')
                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="name">Name:</label>
                    <input type="text" name="name" value="{{ $hospital->name }}" required class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline @error('name') border-red-500 @enderror">
                    @error('name')
                    <p class="text-red-500 text-xs italic">{{ $message }}</p>
                    @enderror
                </div>
                <!-- Repeat for other attributes -->
                <div class="flex items-center justify-between">
                    <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                        Update
                    </button>
                </div>
            </form>
        </div>
    </div>
</x-app-layout>

resources/views/pages/dashboard/hospital/index.blade.php
<x-app-layout>
    <div class="px-4 sm:px-6 lg:px-8 py-8 w-full max-w-9xl mx-auto">
        <div class="max-w-5xl mx-auto mt-8">
            <h1 class="text-2xl font-semibold mb-4">Hospital List</h1>
            <table class="w-full border">
                <thead>
                <tr class="bg-gray-100">
                    <th class="border px-4 py-2">#</th>
                    <th class="border px-4 py-2">Name</th>
                    <th class="border px-4 py-2">Contact</th>
                    <th class="border px-4 py-2">Email</th>
                    <th class="border px-4 py-2">Address</th>
                    <th class="border px-4 py-2">City</th>
                    <th class="border px-4 py-2">Status</th>
                    <th class="border px-4 py-2">Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach ($hospitals as $hospital)
                    <tr>
                        <td class="border px-4 py-2">{{ $hospital->id }}</td>
                        <td class="border px-4 py-2">{{ $hospital->name }}</td>
                        <td class="border px-4 py-2">{{ $hospital->contact_number }}</td>
                        <td class="border px-4 py-2">{{ $hospital->email }}</td>
                        <td class="border px-4 py-2">{{ $hospital->address }}</td>
                        <td class="border px-4 py-2">{{ $hospital->city }}</td>
                        <td class="border px-4 py-2">
                            @if ($hospital->is_approved)
                                <span class="text-green-500">Approved</span>
                            @else
                                <span class="text-red-500">Not Approved</span>
                            @endif
                        </td>

                        <td class="border px-4 py-2">
                            <a href="{{ route('hospitals.show', $hospital->id) }}" class="btn btn-primary bg-amber-500">View</a>
                            <form action="{{ $hospital->is_approved ? route('hospitals.disapprove', $hospital) : route('hospitals.approve', $hospital) }}" method="POST" class="inline">
                                @csrf
                                @method('PUT')
                                <button type="submit" class="bg-{{ $hospital->is_approved ? 'red' : 'blue' }}-500 hover:bg-{{ $hospital->is_approved ? 'red' : 'blue' }}-700 text-white font-bold py-2 px-4 rounded focus:outline-none">
                                    @if ($hospital->is_approved)
                                        Disapprove
                                    @else
                                        Approve
                                    @endif
                                </button>
                            </form>

                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>

        {{ $hospitals->links() }} <!-- Display pagination links -->

        </div>
    </div>
</x-app-layout>