routes/web.php
<?php

use App\Http\Controllers\CampaignController;
use App\Http\Controllers\HospitalController;
use App\Http\Controllers\HospitalLoginController;
use App\Http\Controllers\HospitalServicesController;
use App\Http\Controllers\PatientController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DataFeedController;
use App\Http\Controllers\DashboardController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::post('register', [HospitalController::class, 'register']);

Route::get('login/hospital', [HospitalLoginController::class, 'showLoginForm'])->name('hospital.login');
Route::post('login/hospital', [HospitalLoginController::class, 'login']);



Route::redirect('/', 'login');

Route::middleware(['auth:sanctum', 'verified'])->group(function () {

    // Route for the getting the data feed
    Route::get('/json-data-feed', [DataFeedController::class, 'getDataFeed'])->name('json_data_feed');

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('services',DashboardController::class);
    Route::resource('hospitals', HospitalController::class);
    Route::put('hospitals/approve/{hospital}', [HospitalController::class, 'approve'])->name('hospitals.approve');
    Route::put('hospitals/disapprove/{hospital}', [HospitalController::class, 'disapprove'])->name('hospitals.disapprove');

    Route::fallback(function() {
        return view('pages/utility/404');
    });


});


Route::middleware(['auth:hospital'])->group(function () {
    Route::resource('patients', PatientController::class);
    Route::resource('campaigns', CampaignController::class);
    Route::resource('hospital-services',\App\Http\Controllers\HospitalServicesController::class);

    Route::get('hospital-services/{hospital}/update-view', [HospitalServicesController::class, 'updateServicesView'])
        ->name('hospital-services.update-view');

   /* Route::put('hospital-services/{hospital}', [HospitalServicesController::class, 'updateServices'])
        ->name('hospital-services.update');*/

    Route::get('/hospital/update-password', [HospitalController::class,'editPassword'])->name('hospital.editPassword');
    Route::post('/hospital/update-password', [HospitalController::class,'updatePassword'])->name('hospital.updatePassword');




});

app/Models/Hospital.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Hospital  extends Authenticatable

{
    use HasFactory;

    protected $fillable = [
        'name',
        'contact_number',
        'email',
        'address',
        'city',
        'password',
        'is_approved', // Add this line
    ];

    public function services()
    {
        return $this->belongsToMany(Service::class)
            ->withPivot('status')
            ->withTimestamps();


    }

}

app/Http/Controllers/HospitalController.php
<?php

namespace App\Http\Controllers;

use App\Models\Hospital;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class HospitalController extends Controller
{

    public function register(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'contact_number' => 'required|string|max:255',
            'email' => 'required|email|unique:hospitals',
            'address' => 'required|string|max:255',
            'city' => 'required|string|max:255',
            'password' => 'required|string|min:8|confirmed',
        ]);

        Hospital::create([
            'name' => $request->name,
            'contact_number' => $request->contact_number,
            'email' => $request->email,
            'address' => $request->address,
            'city' => $request->city,
            'password' => Hash::make($request->password),
        ]);

        return redirect()->route('login')->with('success', 'Hospital registered successfully! You can now log in.');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $hospitals = Hospital::paginate(10);
        return view('pages.dashboard.hospital.index', compact('hospitals'));
    }

    public function create()
    {
        return view('pages.dashboard.hospital.create');
    }

    public function store(Request $request)
    {
        // Validation and store logic
    }

    public function edit($id)
    {
        $hospital = Hospital::findOrFail($id);
        return view('pages.dashboard.hospital.edit', compact('hospital'));
    }

    public function update(Request $request, $id)
    {
        $hospital = Hospital::findOrFail($id);

        // Validation and update logic
        $hospital->update($request->all());

        return redirect()->route('hospitals.index')->with('success', 'Hospital updated successfully');
    }

    public function destroy($id)
    {
        // Delete logic
    }

    public function approve(Hospital $hospital)
    {
        $hospital->update(['is_approved' => true]);
        return    $this->index();
    }

    public function disapprove(Hospital $hospital)
    {
        $hospital->update(['is_approved' => false]);
        return redirect()->route('hospitals.index')->with('success', 'Hospital disapproved successfully');
    }

    public function show($id)
    {
        $hospital = Hospital::findOrFail($id);
        return view('pages.dashboard.hospital.show', compact('hospital'));
    }

    public function editPassword()
    {
        return view('pages.hospital.update-password');
    }

    public function updatePassword(Request $request)
    {

        $user = auth()->guard('hospital')->user();

        if (Hash::check($request->current_password, $user->password)) {
            $user->update([
                'password' => Hash::make($request->password),
            ]);

            return redirect()->route('hospital.editPassword')->with('success', 'Password updated successfully.');
        } else {
            return redirect()->route('hospital.editPassword')->with('error', 'Current password is incorrect.');
        }
    }

}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/pages/hospital/campaigns/edit.blade.php
<x-app-layout>
    <div class="px-4 sm:px-6 lg:px-8 py-8 w-full max-w-9xl mx-auto">

        <div class="max-w-md mx-auto mt-8">
            <h1 class="text-2xl font-semibold mb-4">Edit Campaign</h1>
            <form method="POST" action="{{ route('campaigns.update', $campaign->id) }}" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
                @csrf
                @method('PUT')
                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="name">Title:</label>
                    <input type="text" name="title" value="{{ $campaign->title }}" required
                           class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline @error('name') border-red-500 @enderror">
                    @error('name')
                    <p class="text-red-500 text-xs italic">{{ $message }}</p>
                    @enderror
                </div>
                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="name">Description:</label>
                    <input type="text" name="description" value="{{ $campaign->description }}" required
                           class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline @error('name') border-red-500 @enderror">
                    @error('name')
                    <p class="text-red-500 text-xs italic">{{ $message }}</p>
                    @enderror
                </div>
                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="name">Date & Time:</label>
                    <input type="datetime-local" name="datetime" value="{{ $campaign->datetime }}" required
                           class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline @error('name') border-red-500 @enderror">
                    @error('name')
                    <p class="text-red-500 text-xs italic">{{ $message }}</p>
                    @enderror
                </div>
                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="name">Address:</label>
                    <input type="text" name="address" value="{{$campaign->address }}" required
                           class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline @error('name') border-red-500 @enderror">
                    @error('name')
                    <p class="text-red-500 text-xs italic">{{ $message }}</p>
                    @enderror
                </div>
                <div class="mb-4">
                    <label class="block text-gray-700 text-sm font-bold mb-2" for="name">City:</label>
                    <input type="text" name="city" value="{{ $campaign->city }}" required
                           class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline @error('name') border-red-500 @enderror">
                    @error('name')
                    <p class="text-red-500 text-xs italic">{{ $message }}</p>
                    @enderror
                </div>
                <div class="flex items-center justify-between">
                    <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                        Update
                    </button>
                </div>
            </form>
        </div>


    </div>

</x-app-layout>

resources/views/pages/hospital/campaigns/index.blade.php
<x-app-layout>
    <div class="px-4 sm:px-6 lg:px-8 py-8 w-full max-w-9xl mx-auto">

        <!-- Welcome banner -->
        <x-dashboard.welcome-banner />

        <!-- Dashboard actions -->
        <div class="sm:flex sm:justify-between sm:items-center mb-8">

            <!-- Right: Actions -->
            <div class="grid grid-flow-col sm:auto-cols-max justify-start sm:justify-end gap-2">

                <!-- Add view button -->
                <a href="{{ route('campaigns.create') }}"
                   class="bg-green-700 hover:bg-red-700 text-white py-2 px-4 rounded">
                    <span class="hidden xs:block ml-2">Add Campaign</span>
                </a>


            </div>

        </div>

        <table class="w-full border-collapse border">
            <thead>
            <tr>
                <th class="p-4 bg-gray-100 border border-gray-300">ID</th>
                <th class="p-4 bg-gray-100 border border-gray-300">Title</th>
                <th class="p-4 bg-gray-100 border border-gray-300">Description</th>
                <th class="p-4 bg-gray-100 border border-gray-300">Date & Time</th>
                <th class="p-4 bg-gray-100 border border-gray-300">Address</th>
                <th class="p-4 bg-gray-100 border border-gray-300">City</th>
                <th class="p-4 bg-gray-100 border border-gray-300">Actions</th>
                <!-- Other columns -->
            </tr>
            </thead>
            <tbody>
            @foreach($campaigns as $campaign)
                <tr class="bg-white hover:bg-gray-100">
                    <td class="p-4 border border-gray-300">{{ $loop->index+1 }}</td>
                    <td class="p-4 border border-gray-300">{{ $campaign->title }}</td>
                    <td class="p-4 border border-gray-300">{{ $campaign->description }}</td>
                    <td class="p-4 border border-gray-300">{{ $campaign->datetime }}</td>
                    <td class="p-4 border border-gray-300">{{ $campaign->address }}</td>
                    <td class="p-4 border border-gray-300">{{ $campaign->city }}</td>
                    <td class="p-4 border border-gray-300">
                        <a href="{{ route('campaigns.edit', $campaign->id) }}" class="bg-blue-400 hover:bg-blue-600 text-white  py-2 px-4 rounded">Edit</a>
                        <form action="{{ route('campaigns.destroy', $campaign->id) }}" method="POST" class="d-inline">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="bg-red-500 hover:bg-red-600 text-white py-2 px-4 rounded">Delete</button>
                        </form>
                    </td>
                    <!-- Other cells -->
                </tr>
            @endforeach
            </tbody>
        </table>

    {{ $campaigns->links() }} <!-- Display pagination links -->


    </div>
</x-app-layout>