routes/web.php
<?php

use App\Http\Controllers\CampaignController;
use App\Http\Controllers\HospitalController;
use App\Http\Controllers\HospitalLoginController;
use App\Http\Controllers\HospitalServicesController;
use App\Http\Controllers\PatientController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DataFeedController;
use App\Http\Controllers\DashboardController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::post('register', [HospitalController::class, 'register']);

Route::get('login/hospital', [HospitalLoginController::class, 'showLoginForm'])->name('hospital.login');
Route::post('login/hospital', [HospitalLoginController::class, 'login']);



Route::redirect('/', 'login');

Route::middleware(['auth:sanctum', 'verified'])->group(function () {

    // Route for the getting the data feed
    Route::get('/json-data-feed', [DataFeedController::class, 'getDataFeed'])->name('json_data_feed');

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('services',DashboardController::class);
    Route::resource('hospitals', HospitalController::class);
    Route::put('hospitals/approve/{hospital}', [HospitalController::class, 'approve'])->name('hospitals.approve');
    Route::put('hospitals/disapprove/{hospital}', [HospitalController::class, 'disapprove'])->name('hospitals.disapprove');

    Route::fallback(function() {
        return view('pages/utility/404');
    });


});


Route::middleware(['auth:hospital'])->group(function () {
    Route::resource('patients', PatientController::class);
    Route::resource('campaigns', CampaignController::class);
    Route::resource('hospital-services',\App\Http\Controllers\HospitalServicesController::class);

    Route::get('hospital-services/{hospital}/update-view', [HospitalServicesController::class, 'updateServicesView'])
        ->name('hospital-services.update-view');

   /* Route::put('hospital-services/{hospital}', [HospitalServicesController::class, 'updateServices'])
        ->name('hospital-services.update');*/

    Route::get('/hospital/update-password', [HospitalController::class,'editPassword'])->name('hospital.editPassword');
    Route::post('/hospital/update-password', [HospitalController::class,'updatePassword'])->name('hospital.updatePassword');




});

app/Http/Controllers/DashboardController.php
<?php

    namespace App\Http\Controllers;

    use App\Models\Service;
    use Illuminate\Http\Request;
    use Illuminate\Support\Facades\Http;
    use App\Models\DataFeed;
    use Carbon\Carbon;

    class DashboardController extends Controller
    {

        /**
         * Displays the dashboard screen
         *
         * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
         */
        public function index()
        {
            $services = Service::paginate(10);

            return view('pages.dashboard.dashboard', compact('services'));

           // return view('pages/dashboard/dashboard', compact('dataFeed'));
        }
        public function show($id)
        {
            // Display the details of a specific service
        }
        public function create()
        {
            return view('pages.dashboard.services.create');
        }

        public function store(Request $request)
        {
            $validatedData = $request->validate([
                'name' => 'required|string|max:255',
                'status' => 'required|in:Available,Busy',
            ]);

            Service::create($validatedData);

            return redirect()->route('services.index')->with('success', 'Service created successfully');
        }

        public function edit($id)
        {
            $service = Service::findOrFail($id);
            return view('pages.dashboard.services.edit', compact('service'));
        }

        public function update(Request $request, $id)
        {
            $service = Service::findOrFail($id);
            $service->update($request->all());
            return redirect()->route('services.index')->with('success', 'Service updated successfully');
        }

        public function destroy($id)
        {

            $service = Service::findOrFail($id);
            $service->delete();
            return $this->index();
        }
    }

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/pages/dashboard/dashboard.blade.php
<x-app-layout>
    <div class="px-4 sm:px-6 lg:px-8 py-8 w-full max-w-9xl mx-auto">

        <!-- Welcome banner -->
        <x-dashboard.welcome-banner />

        <!-- Dashboard actions -->
        <div class="sm:flex sm:justify-between sm:items-center mb-8">

            <!-- Right: Actions -->
            <div class="grid grid-flow-col sm:auto-cols-max justify-start sm:justify-end gap-2">

                <!-- Add view button -->
                <a href="{{ route('services.create') }}"
                   class="bg-green-700 hover:bg-red-700 text-white py-2 px-4 rounded">
                    <span class="hidden xs:block ml-2">Add Service</span>
                </a>


            </div>

        </div>


            <table  class="w-full border-collapse border table" data-searchable="true">
                <thead>
                <tr>
                    <th class="p-4 bg-gray-100 border border-gray-300">ID</th>
                    <th class="p-4 bg-gray-100 border border-gray-300">Name</th>
                    <th class="p-4 bg-gray-100 border border-gray-300">Status</th>
                    <th class="p-4 bg-gray-100 border border-gray-300">Action</th>
                    <!-- Other columns -->
                </tr>
                </thead>
                <tbody>
                @foreach($services as $service)
                    <tr class="bg-white hover:bg-gray-100">
                        <td class="p-4 border border-gray-300">{{ $loop->index+1 }}</td>
                        <td class="p-4 border border-gray-300">{{ $service->name }}</td>
                        <td class="p-4 border border-gray-300">{{ $service->status }}</td>
                        <td class="p-4 border border-gray-300">
                            <a href="{{ route('services.edit', ['service' => $service->id]) }}"
                               class="bg-blue-400 hover:bg-blue-700 text-white py-2 px-4 rounded">
                                Edit
                            </a>
                            <form method="POST" action="{{ route('services.destroy', $service->id) }}" class="inline">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="text-red-500 hover:text-red-700 focus:outline-none btn">
                                    Delete
                                </button>
                            </form>

                        </td>
                        <!-- Other cells -->
                    </tr>
                @endforeach
                </tbody>
            </table>

        {{ $services->links() }} <!-- Display pagination links -->



    </div>
</x-app-layout>